# https://github.com/boschkundendienst/guacamole-docker-compose
# https://github.com/boschkundendienst/guacamole-docker-compose/issues/12

version: '2.0'

# networks
# create a network 'guacamole' in mode 'bridged'
networks:
  guacamole:
    driver: bridge

# services
services:
  # guacd - this is the container with host network for Wake On Lan
  guacd:
    container_name: guacd
    image: guacamole/guacd
    network_mode: host
    restart: always
    volumes:
    - /opt/guacamole/guacd/drive:/drive:rw
    - /opt/guacamole/guacd/record:/record:rw
  # postgres
  postgres:
    container_name: postgres_for_guacamole
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      guacamole:
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - /opt/guacamole/postgres/data:/var/lib/postgresql/data:Z

  # guacamole
  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guacamole:
    ports:
    - $GUACAMOLE_PORT
    restart: always
